name: Texpresso
description: "News for all"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0 
  video_player: ^2.9.5
  chewie: ^1.11.3
  http: ^1.4.0
  html: ^0.15.6
  url_launcher: ^6.3.1
  amplify_flutter: ^2.6.1
  amplify_auth_cognito: ^2.6.1
  flutter_secure_storage: ^8.0.0
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  package_info_plus: ^8.3.0
  # aggiungi qui solo il package:
  flutter_launcher_icons: ^0.14.3

# configurazione di flutter_launcher_icons va a questo livello,
# NON dentro dev_dependencies
flutter_icons:
  android: true
  ios: true
  # path relativo al tuo asset
  image_path: "lib/resources/Logo.png"

flutter:
  uses-material-design: true
  assets:
    - "lib/resources/"
